### ISSUE TITLE
Help,Thank you very much

### ISSUE THREAD

**Issue by oknixus** [ChengLong/ansible-vim#1]
![1](https://cloud.githubusercontent.com/assets/4592706/6610865/4a783d2e-c8a0-11e4-848b-ce91312343fd.png)
![2](https://cloud.githubusercontent.com/assets/4592706/6610866/4a7e629e-c8a0-11e4-9744-a3eab29d8842.png)

First, when I enter 2 chars, the first line will be selected status,I could knock Enter key for input; But when I enter the third char, the selected status was missing, and I have to knock Ctrl-N to select the right one;
My problem is How to make the right one was selected when I enter the third char,the fourth char...the nth char. 
My englist is not good; Sorry!
I need your help! Thank your very much!

**Comment by ChengLong** [comment]
Hi NixusCN,

I assume you are talking about [AutoComplPop](https://github.com/vim-scripts/AutoComplPop). 
I can't reproduce what you said on Mac and Ubuntu. I suspect it has something to do with your vim setup on Windows (seems like you are using Windows). Try reinstall vim and ONLY install Pathogen  and AutoComplPop
Since this role is for Debian and Ubuntu, sorry that I can't help.

**Comment by oknixus** [comment]
@ChengLong Thank you very much.I has solved the problem: recompile with patches 216+
